### ISSUE TITLE
Co bych přidal

### ISSUE THREAD

**Issue by michalzyka** [jakubboucek/roumen-cz-improve-ui#5]
Zdar, kdysi jsem dělal [podobnej extension](https://chrome.google.com/webstore/detail/rouming-navigation/npdedolejmplhdmnkaeedpipgchmolkm), ale tvůj je lepší a můj asi přestal fungovat a kód už nemám, takže používám ten tvůj :-D

Navrhoval bych pár featur navíc: 
- šipkou dolu dát náhodu
- na S uložit obrázek - to jsem myslim [měl takhle](https://stackoverflow.com/a/17311705)

**Comment by jakubboucek** [comment]
To mě těší, že se líbí. Já už bych bez něj nemohl Rouming používat. Nejvíc mě to štve na mobilu, kde jej nejde použít.
## K nápadům:
- **Šipku dolů** bych neměnil, protože tím scroluju na komentáře. Hodila by se spíše klávesa `R` jako `Random`.
- **Uložení obrázku** je zajímavý nápad. Asi bych použil [pokročilé API moderního browseru](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download).

**Comment by michalzyka** [comment]
Luxus!

**Comment by jakubboucek** [comment]
Tak do hodiny to budeš mít ve svém browseru :) Bylo mi potěšením!

**Comment by michalzyka** [comment]
![Alt Text](https://media.giphy.com/media/WmkqburJqXziM/giphy.gif)
